In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('NLSY_AllVariables.dat',delimiter=' ')

In [4]:
df

,301,1.8967345883,1981,1,3,6.3,-99999,6.3.1,9.5,6.7,...,-99999.26,-99999.27,-99999.28,-99999.29,-99999.30,-99999.31,-99999.32,-99999.33,-99999.34,7
0,302,1.831409,1983,1,3,-99999.0,3.4,9.0,-99999.0,-99999.0,...,-99999,-99999.000000,2,1,2,2,2,1,1.666667,-99999
1,401,0.949808,1980,0,3,-99999.0,7.5,4.2,-99999.0,-99999.0,...,1,1.285714,-99999,-99999,-99999,-99999,-99999,-99999,-99999.000000,-99999
2,802,2.396110,1979,0,3,7.7,7.0,8.2,4.5,9.5,...,0,0.714286,1,2,2,2,2,2,1.833333,8
3,803,2.393750,1982,1,3,7.0,6.1,5.3,5.5,6.9,...,0,0.142857,1,1,1,2,1,1,1.166667,4
4,4301,1.518538,1982,1,3,2.7,1.6,2.5,4.5,2.6,...,-99999,-99999.000000,-99999,-99999,-99999,-99999,-99999,-99999,-99999.000000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2473,1230402,0.390353,1980,0,2,0.2,1.6,3.4,1.0,3.9,...,-99999,-99999.000000,2,1,2,0,2,1,1.333333,6
2474,1230403,0.400590,1984,0,2,-99999.0,4.5,1.9,3.4,4.5,...,2,0.428571,-99999,-99999,-99999,-99999,-99999,-99999,-99999.000000,0
2475,1251501,0.382606,1981,0,2,0.4,-99999.0,6.6,7.7,7.0,...,0,0.428571,1,1,2,2,1,1,1.333333,7
2476,1256601,0.014637,1979,0,2,6.8,7.9,7.7,5.3,4.7,...,0,1.000000,1,1,1,2,2,2,1.500000,0
2477,1266702,0.949808,1983,0,1,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,...,3,2.285714,2,1,3,1,1,1,1.500000,0